// Centralized SEO helpers. Keep canonical/og URLs absolute everywhere.
// Override at build time with VITE_SITE_URL to point at a different domain.
// The production site lives at https://rzifi.com — every canonical, og:url,
// sitemap entry, JSON-LD url and breadcrumb must resolve against that host.
const DEFAULT_SITE_URL = "https://rzifi.com";
const DEFAULT_BING_SITE_VERIFICATION = "0042C7FD5604AA776BACE3344377C74E";

type ViteEnv = {
  VITE_SITE_URL?: string;
  VITE_OG_IMAGE_URL?: string;
  VITE_GTM_ID?: string;
  VITE_GA_MEASUREMENT_ID?: string;
  VITE_GOOGLE_ADS_ID?: string;
  VITE_GOOGLE_ADS_PAGE_VIEW_CONVERSION_LABEL?: string;
  VITE_LINKEDIN_PARTNER_ID?: string;
  VITE_BING_SITE_VERIFICATION?: string;
  VITE_MICROSOFT_CLARITY_ID?: string;
  VITE_PLAUSIBLE_DOMAIN?: string;
  VITE_PLAUSIBLE_SRC?: string;
};
const env: ViteEnv =
  typeof import.meta !== "undefined" && (import.meta as ImportMeta & { env?: ViteEnv }).env
    ? ((import.meta as ImportMeta & { env: ViteEnv }).env ?? {})
    : {};

export const SITE_URL = env.VITE_SITE_URL || DEFAULT_SITE_URL;

/**
 * Canonical URL helper. Returns an absolute URL on SITE_URL with a trailing
 * slash for every non-root, non-file path — that's what Apache 301-redirects
 * to on Hostinger (DirectorySlash). Matching the post-redirect URL in our
 * canonicals / sitemap / og:url avoids the 1-hop redirect penalty.
 *
 * Examples:
 *   absUrl("/")                      → "https://rzifi.com/"
 *   absUrl("/about")                 → "https://rzifi.com/about/"
 *   absUrl("/blog/foo-bar")          → "https://rzifi.com/blog/foo-bar/"
 *   absUrl("/sitemap.xml")           → "https://rzifi.com/sitemap.xml"   (file)
 *   absUrl("/Rizwan_Zafar_Resume.pdf") → "https://rzifi.com/Rizwan_Zafar_Resume.pdf"
 *   absUrl("https://x.com")          → "https://x.com" (external untouched)
 */
export const absUrl = (path: string) => {
  if (path.startsWith("http")) return path;
  const withSlash = path.startsWith("/") ? path : `/${path}`;
  // Don't add trailing slash to file URLs (anything with a dot in the last
  // path segment) or to URLs that already have one.
  const lastSegment = withSlash.split("?")[0].split("#")[0].split("/").pop() ?? "";
  const isFile = lastSegment.includes(".");
  const needsSlash =
    !isFile && withSlash !== "/" && !withSlash.split("?")[0].split("#")[0].endsWith("/");
  const [pathOnly, ...rest] = withSlash.split(/([?#])/);
  const trailing = needsSlash ? `${pathOnly}/${rest.join("")}` : withSlash;
  return `${SITE_URL}${trailing}`;
};

// Default OG image. Self-hosted on rzifi.com via public/og-default.png
// (1200×630, dark + brand-cyan, generated by scripts/generate-og.ts). Keeps
// the social-preview signal entirely on the rzifi.com domain. Override via
// VITE_OG_IMAGE_URL for testing or per-environment cards.
const DEFAULT_OG_IMAGE = `${SITE_URL}/og-default.png`;
export const OG_IMAGE_URL = env.VITE_OG_IMAGE_URL || DEFAULT_OG_IMAGE;

// Google Tag Manager — RETIRED 2026-06-12. The container (GTM-TM5BP98G) held
// UI-built tags duplicating what the code already sends directly (GA4, Ads,
// LinkedIn Insight), so every event double-counted. Single direct-gtag
// pipeline now; leave empty unless deliberately reinstating GTM as the ONLY
// pipeline (then strip the inline tags instead).
export const GTM_ID = env.VITE_GTM_ID ?? "";

// GA4 direct tag — the single analytics pipeline. All site events reach GA4
// via inline gtag() calls (analytics bridge + cal embed funnel scripts).
export const GA_MEASUREMENT_ID = env.VITE_GA_MEASUREMENT_ID ?? "G-F1NK5FJYJY";

// Google Ads base tag for campaign attribution / conversion readiness.
// Keep this alongside GA4 in the direct Google tag fallback so the paid resume
// campaign can be verified even before Ads conversions are imported from GA4.
export const GOOGLE_ADS_ID = env.VITE_GOOGLE_ADS_ID ?? "AW-790961325";
export const GOOGLE_ADS_PAGE_VIEW_CONVERSION_LABEL =
  env.VITE_GOOGLE_ADS_PAGE_VIEW_CONVERSION_LABEL ?? "6HJOCOTfn7ocEK25lPkC";
export const GOOGLE_ADS_PAGE_VIEW_CONVERSION_SEND_TO =
  GOOGLE_ADS_ID && GOOGLE_ADS_PAGE_VIEW_CONVERSION_LABEL
    ? `${GOOGLE_ADS_ID}/${GOOGLE_ADS_PAGE_VIEW_CONVERSION_LABEL}`
    : "";

// LinkedIn Insight Tag. Partner id from Campaign Manager (account 168924577)
// → Signals manager → Sources → Insight Tag. Shipped as a direct tag (not via
// GTM) so the tag verifies and starts building the retargeting audience before
// any GTM publishing round-trip; fires site-wide, conversions are defined in
// Campaign Manager on top of it. Set VITE_LINKEDIN_PARTNER_ID="" to opt out.
// Comma-separated: the live ad account's tag (10373449, created 2026-06-12)
// first, plus the original 3222825 so history in the old account stays intact.
export const LINKEDIN_PARTNER_IDS = (env.VITE_LINKEDIN_PARTNER_ID ?? "10373449,3222825")
  .split(",")
  .map((id) => id.trim())
  .filter(Boolean);
// LinkedIn event-specific conversion for a booked call (Campaign Manager →
// Analyze → Conversion tracking → create "Meeting booked" event conversion,
// then put its numeric id here / in VITE_LINKEDIN_BOOKING_CONVERSION_ID).
// Empty string = the lintrk track call is omitted from the embed script.
export const LINKEDIN_BOOKING_CONVERSION_ID = env.VITE_LINKEDIN_BOOKING_CONVERSION_ID ?? "";

// Optional analytics / webmaster IDs — all direct tags (GTM retired).
export const BING_SITE_VERIFICATION =
  env.VITE_BING_SITE_VERIFICATION || DEFAULT_BING_SITE_VERIFICATION;
export const MICROSOFT_CLARITY_ID = env.VITE_MICROSOFT_CLARITY_ID || "";
export const PLAUSIBLE_DOMAIN = env.VITE_PLAUSIBLE_DOMAIN || "";
export const PLAUSIBLE_SRC = env.VITE_PLAUSIBLE_SRC || "https://plausible.io/js/script.js";

/**
 * Smart-truncate a string at a word / sentence boundary.
 * - Returns the input unchanged if it already fits.
 * - Prefers to end at the last sentence boundary in the right tail of the
 *   slice; otherwise trims to the last word boundary and appends `…`.
 *
 * Used to keep meta titles ≤ 60 chars and meta descriptions ≤ 160 chars
 * across the routes — the source content (frontmatter, taglines) is often
 * longer than the SEO limits, and we don't want to hand-edit 55 markdown
 * files just to fit Google's truncation window.
 */
export function trimToMax(raw: string, max: number): string {
  if (raw.length <= max) return raw;
  const slice = raw.slice(0, max);
  const lastSentence = Math.max(slice.lastIndexOf(". "), slice.lastIndexOf(".\n"));
  if (lastSentence > max * 0.6) return slice.slice(0, lastSentence + 1);
  const lastSpace = slice.lastIndexOf(" ");
  return (lastSpace > max * 0.6 ? slice.slice(0, lastSpace) : slice).trim() + "…";
}

/**
 * Build a `<title>` tag value that:
 *   1. Uses the explicit `meta` override if it's already SEO-tight.
 *   2. Otherwise appends " | Rizwan Zafar" if the combined string fits ≤ max.
 *   3. Otherwise smart-truncates the raw title to ≤ max.
 */
export function titleFor(
  raw: string,
  options?: { meta?: string; max?: number; suffix?: string },
): string {
  const max = options?.max ?? 60;
  const suffix = options?.suffix ?? " | Rizwan Zafar";
  // NEVER machine-truncate a <title>: Google indexes the full text and only
  // truncates the DISPLAY, while a baked "…" wastes keywords and is what AI
  // engines show when citing the page (2026-06-12 audit: 58 pages shipped
  // ellipsised titles). Long raw titles ship whole, just without the suffix;
  // trimToMax remains for meta DESCRIPTIONS only.
  if (options?.meta) return options.meta;
  const withSuffix = `${raw}${suffix}`;
  return withSuffix.length <= max ? withSuffix : raw;
}

export const SITE_KEYWORDS = [
  "payments product executive Dubai",
  "fintech product leader MENA",
  "payment infrastructure product leader",
  "cross-border payments expert",
  "settlement reconciliation payments",
  "merchant onboarding KYC KYB",
  "AML CFT payments",
  "payment fraud risk management",
  "regulated fintech platforms",
  "Visa Mastercard product management",
  "Stripe Adyen Wise Thunes payments",
  "SWIFT ISO 20022 payments",
  "payment acceptance",
  "payment APIs",
  "wallets and DCB",
  "BNPL product",
].join(", ");
