// Centralized SEO helpers. Keep canonical/og URLs absolute everywhere.
// Override at build time with VITE_SITE_URL to point at a different domain.
// The production site lives at https://rzifi.com — every canonical, og:url,
// sitemap entry, JSON-LD url and breadcrumb must resolve against that host.
const DEFAULT_SITE_URL = "https://rzifi.com";
const DEFAULT_BING_SITE_VERIFICATION = "0042C7FD5604AA776BACE3344377C74E";

type ViteEnv = {
  VITE_SITE_URL?: string;
  VITE_OG_IMAGE_URL?: string;
  VITE_GTM_ID?: string;
  VITE_GA_MEASUREMENT_ID?: string;
  VITE_BING_SITE_VERIFICATION?: string;
  VITE_MICROSOFT_CLARITY_ID?: string;
  VITE_PLAUSIBLE_DOMAIN?: string;
  VITE_PLAUSIBLE_SRC?: string;
};
const env: ViteEnv =
  typeof import.meta !== "undefined" && (import.meta as ImportMeta & { env?: ViteEnv }).env
    ? ((import.meta as ImportMeta & { env: ViteEnv }).env ?? {})
    : {};

export const SITE_URL = env.VITE_SITE_URL || DEFAULT_SITE_URL;

/**
 * Canonical URL helper. Returns an absolute URL on SITE_URL with a trailing
 * slash for every non-root, non-file path — that's what Apache 301-redirects
 * to on Hostinger (DirectorySlash). Matching the post-redirect URL in our
 * canonicals / sitemap / og:url avoids the 1-hop redirect penalty.
 *
 * Examples:
 *   absUrl("/")                      → "https://rzifi.com/"
 *   absUrl("/about")                 → "https://rzifi.com/about/"
 *   absUrl("/blog/foo-bar")          → "https://rzifi.com/blog/foo-bar/"
 *   absUrl("/sitemap.xml")           → "https://rzifi.com/sitemap.xml"   (file)
 *   absUrl("/Rizwan_Zafar_Resume.pdf") → "https://rzifi.com/Rizwan_Zafar_Resume.pdf"
 *   absUrl("https://x.com")          → "https://x.com" (external untouched)
 */
export const absUrl = (path: string) => {
  if (path.startsWith("http")) return path;
  const withSlash = path.startsWith("/") ? path : `/${path}`;
  // Don't add trailing slash to file URLs (anything with a dot in the last
  // path segment) or to URLs that already have one.
  const lastSegment = withSlash.split("?")[0].split("#")[0].split("/").pop() ?? "";
  const isFile = lastSegment.includes(".");
  const needsSlash =
    !isFile && withSlash !== "/" && !withSlash.split("?")[0].split("#")[0].endsWith("/");
  const [pathOnly, ...rest] = withSlash.split(/([?#])/);
  const trailing = needsSlash ? `${pathOnly}/${rest.join("")}` : withSlash;
  return `${SITE_URL}${trailing}`;
};

// Default OG image. Self-hosted on rzifi.com via public/og-default.png
// (1200×630, dark + brand-cyan, generated by scripts/generate-og.ts). Keeps
// the social-preview signal entirely on the rzifi.com domain. Override via
// VITE_OG_IMAGE_URL for testing or per-environment cards.
const DEFAULT_OG_IMAGE = `${SITE_URL}/og-default.png`;
export const OG_IMAGE_URL = env.VITE_OG_IMAGE_URL || DEFAULT_OG_IMAGE;

// Google Tag Manager. Set VITE_GTM_ID in .env.local (or empty) to opt out for dev.
// The container live in production is GTM-TM5BP98G.
export const GTM_ID = env.VITE_GTM_ID ?? "GTM-TM5BP98G";

// Direct GA4 fallback. The GTM container can still own richer marketing tags,
// but a first-party Google tag keeps page views and key events live if GTM is
// paused, unpublished, or blocked by container quality issues.
export const GA_MEASUREMENT_ID = env.VITE_GA_MEASUREMENT_ID ?? "G-F1NK5FJYJY";

// Optional analytics / webmaster IDs.
// Keep GA4, Google Ads, LinkedIn Insight, Meta Pixel and other marketing tags
// in GTM. These direct toggles are for tools that are useful outside GTM or
// need a page-level verification meta tag.
export const BING_SITE_VERIFICATION =
  env.VITE_BING_SITE_VERIFICATION || DEFAULT_BING_SITE_VERIFICATION;
export const MICROSOFT_CLARITY_ID = env.VITE_MICROSOFT_CLARITY_ID || "";
export const PLAUSIBLE_DOMAIN = env.VITE_PLAUSIBLE_DOMAIN || "";
export const PLAUSIBLE_SRC = env.VITE_PLAUSIBLE_SRC || "https://plausible.io/js/script.js";

/**
 * Smart-truncate a string at a word / sentence boundary.
 * - Returns the input unchanged if it already fits.
 * - Prefers to end at the last sentence boundary in the right tail of the
 *   slice; otherwise trims to the last word boundary and appends `…`.
 *
 * Used to keep meta titles ≤ 60 chars and meta descriptions ≤ 160 chars
 * across the routes — the source content (frontmatter, taglines) is often
 * longer than the SEO limits, and we don't want to hand-edit 55 markdown
 * files just to fit Google's truncation window.
 */
export function trimToMax(raw: string, max: number): string {
  if (raw.length <= max) return raw;
  const slice = raw.slice(0, max);
  const lastSentence = Math.max(slice.lastIndexOf(". "), slice.lastIndexOf(".\n"));
  if (lastSentence > max * 0.6) return slice.slice(0, lastSentence + 1);
  const lastSpace = slice.lastIndexOf(" ");
  return (lastSpace > max * 0.6 ? slice.slice(0, lastSpace) : slice).trim() + "…";
}

/**
 * Build a `<title>` tag value that:
 *   1. Uses the explicit `meta` override if it's already SEO-tight.
 *   2. Otherwise appends " | Rizwan Zafar" if the combined string fits ≤ max.
 *   3. Otherwise smart-truncates the raw title to ≤ max.
 */
export function titleFor(
  raw: string,
  options?: { meta?: string; max?: number; suffix?: string },
): string {
  const max = options?.max ?? 60;
  const suffix = options?.suffix ?? " | Rizwan Zafar";
  if (options?.meta)
    return options.meta.length <= max ? options.meta : trimToMax(options.meta, max);
  const withSuffix = `${raw}${suffix}`;
  if (withSuffix.length <= max) return withSuffix;
  if (raw.length <= max) return raw;
  return trimToMax(raw, max);
}

export const SITE_KEYWORDS = [
  "payments product executive Dubai",
  "fintech product leader MENA",
  "payment infrastructure product leader",
  "cross-border payments expert",
  "settlement reconciliation payments",
  "merchant onboarding KYC KYB",
  "AML CFT payments",
  "payment fraud risk management",
  "regulated fintech platforms",
  "Visa Mastercard product management",
  "Stripe Adyen Wise Thunes payments",
  "SWIFT ISO 20022 payments",
  "payment acceptance",
  "payment APIs",
  "wallets and DCB",
  "BNPL product",
].join(", ");
