// Centralized SEO helpers. Keep canonical/og URLs absolute everywhere.
// Override at build time with VITE_SITE_URL to point at a different domain.
// The production site lives at https://rzifi.com — every canonical, og:url,
// sitemap entry, JSON-LD url and breadcrumb must resolve against that host.
const DEFAULT_SITE_URL = "https://rzifi.com";

type ViteEnv = {
  VITE_SITE_URL?: string;
  VITE_OG_IMAGE_URL?: string;
  VITE_GTM_ID?: string;
};
const env: ViteEnv =
  typeof import.meta !== "undefined" && (import.meta as ImportMeta & { env?: ViteEnv }).env
    ? ((import.meta as ImportMeta & { env: ViteEnv }).env ?? {})
    : {};

export const SITE_URL = env.VITE_SITE_URL || DEFAULT_SITE_URL;

export const absUrl = (path: string) =>
  path.startsWith("http") ? path : `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;

// Default OG image. Self-hosted on rzifi.com via public/og-default.png
// (1200×630, dark + brand-cyan, generated by scripts/generate-og.ts). Keeps
// the social-preview signal entirely on the rzifi.com domain. Override via
// VITE_OG_IMAGE_URL for testing or per-environment cards.
const DEFAULT_OG_IMAGE = `${SITE_URL}/og-default.png`;
export const OG_IMAGE_URL = env.VITE_OG_IMAGE_URL || DEFAULT_OG_IMAGE;

// Google Tag Manager. Set VITE_GTM_ID in .env.local (or empty) to opt out for dev.
// The container live in production is GTM-TM5BP98G.
export const GTM_ID = env.VITE_GTM_ID ?? "GTM-TM5BP98G";

export const SITE_KEYWORDS = [
  "payments product executive Dubai",
  "fintech product leader MENA",
  "payment infrastructure product leader",
  "cross-border payments expert",
  "settlement reconciliation payments",
  "merchant onboarding KYC KYB",
  "AML CFT payments",
  "payment fraud risk management",
  "regulated fintech platforms",
  "Visa Mastercard product management",
  "Stripe Adyen Wise Thunes payments",
  "SWIFT ISO 20022 payments",
  "payment acceptance",
  "payment APIs",
  "wallets and DCB",
  "BNPL product",
].join(", ");
