#!/usr/bin/env bun
// Build-time world-map generator. Emits STATIC SVG data — no client-side
// dotted-map import, nothing hydrates. Run: bun scripts/gen-map.mjs
// Output: src/data/world-map.generated.ts (committed; re-run if markets change).
//
// The generated dot grid is the abstract "editorial" world map; the WorldMap
// component composes it with market pins + hub arcs and animates only those
// (CSS). Fill is applied via a parent <g> so we don't repeat a colour string
// on every one of ~1,200 circles (keeps the inlined SVG lean).
import { writeFileSync } from "node:fs";
import DottedMap from "dotted-map";
import { markets, mapHub } from "../src/data/markets.ts";

const HEIGHT = 40; // ~1,150 dots — legible but light once gzipped
const map = new DottedMap({ height: HEIGHT, grid: "diagonal" });

const rawSvg = map.getSVG({
  radius: 0.32,
  color: "#111111",
  shape: "circle",
  backgroundColor: "transparent",
});

const viewBox = rawSvg.match(/viewBox="([^"]+)"/)?.[1] ?? "0 0 80 40";

// Inner circles only, with the per-circle fill stripped (applied on the <g>).
const dots = rawSvg
  .replace(/^[\s\S]*?<svg[^>]*>/, "")
  .replace(/<\/svg>\s*$/, "")
  .replace(/\s*fill="[^"]*"/g, "")
  .replace(/\s+/g, " ")
  .trim();

const project = ({ lat, lng }) => {
  const { x, y } = map.getPin({ lat, lng });
  return { x: Math.round(x * 100) / 100, y: Math.round(y * 100) / 100 };
};

const hub = { ...project(mapHub), city: mapHub.city };
const pins = markets.map((m) => ({ key: m.key, name: m.name, ...project(m) }));

const out = `// AUTO-GENERATED by scripts/gen-map.mjs — do not edit by hand.
// Static dotted world map + projected market/hub coordinates. Re-run
// \`bun scripts/gen-map.mjs\` after changing src/data/markets.ts.
export const worldMap = {
  viewBox: ${JSON.stringify(viewBox)},
  dots: ${JSON.stringify(dots)},
  hub: ${JSON.stringify(hub)},
  pins: ${JSON.stringify(pins)},
} as const;
`;

writeFileSync("src/data/world-map.generated.ts", out);
console.log(
  `✓ world-map.generated.ts — viewBox ${viewBox}, ${pins.length} pins, dots ${(dots.length / 1024).toFixed(1)}KB`,
);
