/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as ProductWorkIndexRouteImport } from './routes/product-work.index'
import { Route as ForIndexRouteImport } from './routes/for.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TopicsHubRouteImport } from './routes/topics.$hub'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProductWorkSlugRouteImport } from './routes/product-work.$slug'
import { Route as ForAudienceRouteImport } from './routes/for.$audience'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopicsRoute,
} as any)
const ProductWorkIndexRoute = ProductWorkIndexRouteImport.update({
  id: '/product-work/',
  path: '/product-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForIndexRoute = ForIndexRouteImport.update({
  id: '/for/',
  path: '/for/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsHubRoute = TopicsHubRouteImport.update({
  id: '/$hub',
  path: '/$hub',
  getParentRoute: () => TopicsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductWorkSlugRoute = ProductWorkSlugRouteImport.update({
  id: '/product-work/$slug',
  path: '/product-work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAudienceRoute = ForAudienceRouteImport.update({
  id: '/for/$audience',
  path: '/for/$audience',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/for/$audience': typeof ForAudienceRoute
  '/product-work/$slug': typeof ProductWorkSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/topics/$hub': typeof TopicsHubRoute
  '/blog/': typeof BlogIndexRoute
  '/for/': typeof ForIndexRoute
  '/product-work/': typeof ProductWorkIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/for/$audience': typeof ForAudienceRoute
  '/product-work/$slug': typeof ProductWorkSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/topics/$hub': typeof TopicsHubRoute
  '/blog': typeof BlogIndexRoute
  '/for': typeof ForIndexRoute
  '/product-work': typeof ProductWorkIndexRoute
  '/topics': typeof TopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/for/$audience': typeof ForAudienceRoute
  '/product-work/$slug': typeof ProductWorkSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/topics/$hub': typeof TopicsHubRoute
  '/blog/': typeof BlogIndexRoute
  '/for/': typeof ForIndexRoute
  '/product-work/': typeof ProductWorkIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/media'
    | '/products'
    | '/resume'
    | '/sitemap'
    | '/sitemap.xml'
    | '/topics'
    | '/blog/$slug'
    | '/for/$audience'
    | '/product-work/$slug'
    | '/products/$slug'
    | '/topics/$hub'
    | '/blog/'
    | '/for/'
    | '/product-work/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/media'
    | '/products'
    | '/resume'
    | '/sitemap'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/for/$audience'
    | '/product-work/$slug'
    | '/products/$slug'
    | '/topics/$hub'
    | '/blog'
    | '/for'
    | '/product-work'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/media'
    | '/products'
    | '/resume'
    | '/sitemap'
    | '/sitemap.xml'
    | '/topics'
    | '/blog/$slug'
    | '/for/$audience'
    | '/product-work/$slug'
    | '/products/$slug'
    | '/topics/$hub'
    | '/blog/'
    | '/for/'
    | '/product-work/'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MediaRoute: typeof MediaRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  ForAudienceRoute: typeof ForAudienceRoute
  ProductWorkSlugRoute: typeof ProductWorkSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ForIndexRoute: typeof ForIndexRoute
  ProductWorkIndexRoute: typeof ProductWorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/product-work/': {
      id: '/product-work/'
      path: '/product-work'
      fullPath: '/product-work/'
      preLoaderRoute: typeof ProductWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/': {
      id: '/for/'
      path: '/for'
      fullPath: '/for/'
      preLoaderRoute: typeof ForIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$hub': {
      id: '/topics/$hub'
      path: '/$hub'
      fullPath: '/topics/$hub'
      preLoaderRoute: typeof TopicsHubRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/product-work/$slug': {
      id: '/product-work/$slug'
      path: '/product-work/$slug'
      fullPath: '/product-work/$slug'
      preLoaderRoute: typeof ProductWorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/$audience': {
      id: '/for/$audience'
      path: '/for/$audience'
      fullPath: '/for/$audience'
      preLoaderRoute: typeof ForAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface TopicsRouteChildren {
  TopicsHubRoute: typeof TopicsHubRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsHubRoute: TopicsHubRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MediaRoute: MediaRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResumeRoute: ResumeRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopicsRoute: TopicsRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  ForAudienceRoute: ForAudienceRoute,
  ProductWorkSlugRoute: ProductWorkSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ForIndexRoute: ForIndexRoute,
  ProductWorkIndexRoute: ProductWorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
